modules/media/backend/controllers/AlbumController.php
<?php

namespace modules\media\backend\controllers;

use Yii;
use common\models\Album;
use modules\media\backend\models\search\AlbumSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AlbumController implements the CRUD actions for Album model.
 */
class AlbumController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Album models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AlbumSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Album model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Album();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Album model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Album model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Album model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Album the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Album::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/media/backend/controllers/MediaController.php
<?php

namespace modules\media\backend\controllers;

use common\models\Album;
use Yii;
use common\models\Media;
use modules\media\backend\models\search\MediaSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MediaController implements the CRUD actions for Media model.
 */
class MediaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Media models.
     * @param $album_id
     * @return mixed
     */
    public function actionIndex($album_id)
    {
        $searchModel = new MediaSearch();
        $params = Yii::$app->request->queryParams;
        $album = Album::find()->where(['id' => $album_id])->one();
        $params['MediaSearch']['album_id'] = $album->id;
        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'album' => $album
        ]);
    }

    /**
     * Creates a new Media model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param $album_id
     * @return mixed
     */
    public function actionCreate($album_id)
    {
        $model = new Media();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'album_id' => $album_id]);
        } else {
            $album = Album::find()->where(['id' => $album_id])->one();
            return $this->render('create', [
                'model' => $model,
                'album' => $album
            ]);
        }
    }

    /**
     * Updates an existing Media model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $albumId = $model->album_id;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'album_id' => $albumId]);
        } else {
            $album = Album::find()->where(['id' => $albumId])->one();
            return $this->render('update', [
                'model' => $model,
                'album' => $album
            ]);
        }
    }

    /**
     * Deletes an existing Media model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $albumId = $model->album_id;
        $model->delete();
        return $this->redirect(['index', 'album_id' => $albumId]);
    }

    /**
     * Finds the Media model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Media the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Media::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/media/backend/views/album/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use modules\core\components\widgets\FileInput;

/* @var $this yii\web\View */
/* @var $model common\models\FridaySermon */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="nav-tabs-custom">

    <?= $this->render('@modules/media/backend/views/album/parts/_tabs', [
        'album' => $model,
        'buttons' => [
            Html::a('Назад', ['index'], ['class' => 'btn btn-default btn-sm']),
        ]
    ]); ?>
    <?php $form = ActiveForm::begin(); ?>
    <div class="box-body">
        <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'media_type_id')->dropDownList(
            \common\models\MediaType::find()->select(['title', 'id'])->indexBy('id')->column(),
            ['prompt' => 'Выберите тип']
        ); ?>
    </div>
    <div class="box-footer">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

modules/media/backend/views/album/create.php
<?php
/* @var $this yii\web\View */
/* @var $model common\models\FridaySermon */

$this->title = 'Альбом: Создание';
$this->params['breadcrumbs'][] = ['label' => 'Альбом', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Создание';
?>
<?= $this->render('_form', [
    'model' => $model,
]) ?>

modules/media/backend/views/album/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel modules\media\backend\models\search\AlbumSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Альбомы';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">
            <? if (Yii::$app->user->can(Yii::$app->controller->module->id . '.album.create')): ?>
                <?= Html::a('Добавить...', ['create'], ['class' => 'btn btn-block btn-success btn-sm']) ?>
            <? endif; ?>
        </h3>
        <div class="box-tools pull-right"></div>
    </div>
    <div class="box-body">
        <?php Pjax::begin(); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'title',
                'description',
                [
                    'attribute' => 'media_type_id',
                    'value' => function ($data){
                        return $data->getMediaType()->one()->title;
                    },
                    'filter' => \common\models\MediaType::getForDropdownList()
                ],
                [
                    'class' => 'modules\core\backend\components\grid\ActionColumn',
                    'template'=>'{update}  {delete}',
                    'headerOptions' => ['style' => 'width:50px;'],
                    'permissions' => true
                ],
            ],
        ]); ?>
        <?php Pjax::end(); ?>
    </div>
</div>

modules/media/backend/views/album/parts/_tabs.php
<?php
use yii\helpers\Html;
?>
<ul class="nav nav-tabs pull-right">
    <? if(!$album->isNewRecord):?>
        <li<? if(in_array(Yii::$app->controller->id, ['media'])):?> class="active"<? endif;?>>
            <?= Html::a('Элементы', ['media/index', 'album_id' => $album->id]) ?>
        </li>
    <? endif;?>
    <li<? if(in_array(Yii::$app->controller->id, ['album'])):?> class="active"<? endif;?>>
        <? if(!$album->isNewRecord):?>
            <?= Html::a('Ред. альбом', ['album/update', 'id' => $album->id]) ?>
        <? else:?>
            <?= Html::a('Создать альбом', ['album/create']) ?>
        <? endif;?>
    </li>
    <li class="pull-left header">
        <div class="box-title btn-group">
            <? if(isset($buttons)):?>
                <?=implode('', $buttons)?>
            <? endif;?>
        </div>
    </li>
</ul>

modules/media/backend/views/album/update.php
<?php
/* @var $this yii\web\View */
/* @var $model common\models\FridaySermon */

$this->title = 'Альбом: Редактирование';
$this->params['breadcrumbs'][] = ['label' => 'Альбом', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<?= $this->render('_form', [
    'model' => $model,
]) ?>